image: maven:3.5.3-jdk-8

stages:
    - validate
    - test
    - package
    - deploy
    
Validate:
    stage: validate
    script:
        - ./mvnw validate
    tags:
        - validate

Test:
    stage: test
    script:
        - ./mvnw test
    except:
        - master
    tags:
        - test
    
Package:
    stage: package
    script:
        - ./mvnw package -DskipTests
    tags:
        - package

Deploy:
    stage: deploy
    script:
        - echo "cp /builds/aal-ss-18/data-engine-user-interface/target/data-engine-user-interface.jar /root/.iolite/apps" 
    only:
        - dev
    tags:
        - deploy
