image: maven:3.5.3-jdk-8

stages:
    - validate
    - test
    - package
    - deploy
    
Validate:
    stage: validate
    script:
        - ./mvnw validate
    tags:
        - validate

Test:
    stage: test
    script:
        - ./mvnw test
    except:
        - master
        - dev
    tags:
        - test
    
Package:
    stage: package
    script:
        - ./mvnw clean package
    tags:
        - package
    only:
        - master
        - dev
    artifacts:
        untracked: true
        paths:
            - binaries/

Deploy:
    stage: deploy
    script:
        - echo DEPLOY HERE
    only:
        - dev
    tags:
        - deploy
